cc_binary(
    name = "main",
    srcs = ["src/main.cpp"]
)

cc_library(
    name = "some",
    srcs = [
        "include/something.h",
        "src/something.cpp"
    ],
    includes = ["include"],
    hdrs = ["include/something.h"]
)
